baseURL = "/"
title   = "Helgen Technologies"
languageCode = "en-US"
theme = "helgen"
pluralizelisttitles = false

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


PygmentsCodeFences = true
PygmentsStyle = "monokai"


[languages]
  [languages.en]
      languageCode = 'en-US'
      languageName = 'English'
      weight = 0
  [languages.es]  
      languageCode = 'es-MX'
      languageName = 'Spanish'


pagination.pagersize  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a MIT License." 

# googleAnalytics = "G-7RCGLMFCLK"
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false


[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "gibranlp"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]

  customCSS = [
  "../../css/animate.css",
  "../../css/bootstrap.css",
  "../../css/et-line-icons.css",
  "../../css/font-awesome.min.css",
  "../../css/extralayers.css",
  "../../css/settings.css",
  "../../css/magnific-popup.css",
  "../../css/owl.carousel.css",
  "../../css/owl.transitions.css",
  "../../css/full-slider.css",
  "../../css/text-effect.css",
  "../../css/menu-hamburger.css",
  "../../css/style.css",
  "../../css/responsive.css"]
  
  customJS  = ["../../js/jquery.min.js",
  "../../js/modernizr.js",
  "../../js/bootstrap.js",
  "../../js/bootstrap-hover-dropdown.js",
  "https://code.jquery.com/jquery-2.2.0.min.js",
  "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js",
  "../../js/jquery.easing.1.3.js",
  "../../js/skrollr.min.js",
  "../../js/smooth-scroll.js",
  "../../js/jquery.appear.js",
  "../../js/wow.min.js",
  "../../js/page-scroll.js",
  "../../js/jquery.easypiechart.js",
  "../../js/jquery.parallax-1.1.3.js",
  "../../js/jquery.isotope.min.js",
  "../../js/owl.carousel.min.js", 
  "../../js/jquery.magnific-popup.min.js",
  "../../js/popup-gallery.js",
  "../../js/text-effect.js",
  "../../js/jquery.tools.min.js",
  "../../js/jquery.revolution.js",
  "../../js/counter.js",
  "../../js/jquery.countTo.js",
  "../../js/jquery.fitvids.js",
  "../../js/imagesloaded.pkgd.min.js",
  "../../js/classie.js",
  "../../js/hamburger-menu.js",
  "../../js/main.js"]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "We'll give your company superpowers"
  keywords= "actionable,advanced,advancement,approach,awards,business,careers,clients,competitive,contact,continuous,decision,decisions,digital,dynamic,edge,efficiency,elevate,embrace,ensure,ensuring,excellence,founded,future,harnesses,have,heights,helgen,home,informed,innovating,insights,intelligence,ireland,just,keeps,kerry,killorglin,maintenance,make,making,market,mexico,navigation,operational,partners,peak,performance,platform,power,presence,press,proactive,products,reliability,republic,rosie,rosiepi,running,schedule,securing,services,strategies,systems,techtechnologies,technology,today,toggle,transforming,twins,unlock,unparalleled"
  images = [""]

  homeSubtitle = "Your Automated Workforce"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
   # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .post-content.

#### Main Menu
[menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 1

  [[languages.es.menu.main]]
    identifier = "home"
    name       = "Inicio"
    url        = "/"
    weight     = 1

  [[languages.en.menu.main]]
    identifier = "services"
    name       = "Products & Services"
    url        = "https://helgen.tech/#collapse1"
    weight     = 2

  [[languages.es.menu.main]]
    identifier = "services"
    name       = "Productos & Servicios"
    url        = "https://helgen.tech/#collapse1"
    weight     = 2
    
[[languages.en.menu.main]]
    parent = "services"
    name = "Advanced Technology Maintenance"
    url = "atm/"

[[languages.es.menu.main]]
    parent = "services"
    name = "Mantenimiento Avanzado de Tecnología"
    url = "atm/"

[[languages.en.menu.main]]
    parent = "services"
    identifier = "rosiepi"
    name       = "ROSIEPi"
    url        = "rosiepi/"
    weight     = 1

[[languages.es.menu.main]]
    parent = "services"
    identifier = "rosiepies"
    name       = "ROSIEPi"
    url        = "rosiepi/"
    weight     = 1


  [[languages.en.menu.main]]
    identifier = "about"
    name       = "About Us"
    url        = "about/"
    weight     = 3
  
  [[languages.es.menu.main]]
    identifier = "about"
    name       = "Nosotros"
    url        = "about/"
    weight     = 3
  
  [[languages.en.menu.main]]
    identifier = "careers"
    name       = "Careers"
    url        = "careers/"
    weight     = 4

  [[languages.es.menu.main]]
    identifier = "careers"
    name       = "Carreras"
    url        = "careers/"
    weight     = 4
  
  #[[menu.main]]
  #  identifier = "timeline"
  #  name       = "Blog"
  #  url        = "timeline/"
  #  weight     = 6
  
  [[languages.en.menu.main]]
  identifier = "press"
    name       = "Press"
    url        = "press/"
    weight     = 5
  
  [[languages.es.menu.main]]
  identifier = "prensa"
    name       = "Prensa"
    url        = "press/"
    weight     = 5
  
  [[languages.en.menu.main]]
    identifier = "schedule"
    name       = "Schedule a Call"
    url        = "https://calendly.com/helgentech/intro-to-helgen-technologies"
    weight     = 7

  [[languages.es.menu.main]]
    identifier = "schedule"
    name       = "Contáctanos"
    url        = "https://calendly.com/helgentech/intro-to-helgen-technologies"
    weight     = 7
  
  [[languages.en.menu.main]]
    identifier = "landing"
    name       = "Landing"
    url        = "landing/"
    weight     = 8
  [languages.en.menu.main.params]
    hidden = true


  [[languages.es.menu.main]]
    identifier = "Destino"
    name       = "Landing"
    url        = "landing/"
    weight     = 8
  [languages.es.menu.main.params]
    hidden     = true
  
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true